/****** DIM-CATEGORIAS  ******/
SELECT [CODIGO_CATEGORIA]
      ,[CATEGORIA]
  FROM [master].[DB_FLIPBOARD].[TBL_CATEGORIA]
/****** DIM-COMENTARIOS  ******/
SELECT [CODIGO_COMENTARIO]
      ,[CONTENIDO]
      ,[FECHA]
  FROM [master].[DB_FLIPBOARD].[TBL_COMENTARIOS]
/****** DIM-HISTORIAL_ACCESOS  ******/
SELECT [CODIGO_USUARIO]
      ,[FECHA_ACCESO]
  FROM [master].[DB_FLIPBOARD].[TBL_HISTORIAL_ACCESOS]
/****** DIM-LUGARES  ******/
SELECT [CODIGO_LUGAR]
      ,[CODIGO_LUGAR_PADRE]
      ,[CODIGO_TIPO_LUGAR]
      ,[NOMBRE_LUGAR]
  FROM [master].[DB_FLIPBOARD].[TBL_LUGARES]
/****** DIM-NOTICIAS  ******/
SELECT [CODIGO_NOTICIA]
      ,[AUTOR_NOTICIA]
      ,[TITULO_NOTICIA]
      ,[FECHA_PUBLICACION]
  FROM [master].[DB_FLIPBOARD].[TBL_NOTICIAS]
/****** DIM-TIPO_LUGAR  ******/
SELECT [CODIGO_TIPO_LUGAR]
      ,[TIPO_LUGAR]
  FROM [master].[DB_FLIPBOARD].[TBL_TIPO_LUGAR]
/****** DIM-TIPO_USUARIO  ******/
SELECT [CODIGO_TIPO_USUARIO]
      ,[TIPO_USUARIO]
  FROM [master].[DB_FLIPBOARD].[TBL_TIPOS_USUARIO]
/****** DIM-USUARIOS  ******/
SELECT [CODIGO_USUARIO]
      ,[CODIGO_TIPO_USUARIO]
      ,[NOMBRE_USUARIO]
      ,[URL_FOTO_PERFIL]
      ,[FECHA_REGISTRO]
  FROM [master].[DB_FLIPBOARD].[TBL_USUARIOS]